[package]
name = "argo"
version.workspace = true
edition.workspace = true

[dependencies]
argo-theme = { path = "../argo-theme" }
argo-ui = { path = "../argo-ui" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "argo"
path = "src/main.rs"
